spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:items
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

pokemon:
  service:
    url: https://pokeapi.co/api/v2/pokemon
server:
  port: 8091

